github: {
    "version": {},
    "author": "yinjie",
    "hostname": "https://github.com/yj1438/",
    "pages_hostname": "http://yj1438.github.io/"
}
source: ./
destination: ./_site
plugins: ./_plugins
safe: true

# Conversion
#markdown: kramdown
#markdown: kramdown
highlighter: pygments
markdown: rdiscount
rdiscount:
   extensions:
     - footnotes
#redcarpet:
#    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
lsi: false
excerpt_separator: "\n\n\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname

encoding: "utf-8"
markdown_ext: markdown,mkd,mkdn,md