# Site Settings
title:               Yinjie's github
tagline:             A personal tech notes site
description:        
baseurl:             ""
url:                #"https://lenpaul.github.io"
github:
  url:               "https://github.com/yj1438/"
  io_url:            "https://yj1438.github.io/"
author:
  name:              "Yin Jie"
  email:             "yj1438@163.com"
  github:            "https://github.com/yj1438/"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            20
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
kramdown:
    input: GFM
    hard_wrap: false
    math_engine: mathjax

highlighter:         rouge
permalink:           none

lsi: false
excerpt_separator: "\n\n\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 0.0.0.0

encoding: "utf-8"
markdown_ext: markdown,mkd,mkdn,md

gems:                [jekyll-paginate]
